/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrenotaSlugRouteImport } from './routes/prenota.$slug'
import { Route as ConsensoTokenRouteImport } from './routes/consenso.$token'
import { Route as AuthenticatedStatisticheRouteImport } from './routes/_authenticated/statistiche'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedMagazzinoRouteImport } from './routes/_authenticated/magazzino'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedClientiRouteImport } from './routes/_authenticated/clienti'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaSlugRoute = PrenotaSlugRouteImport.update({
  id: '/prenota/$slug',
  path: '/prenota/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsensoTokenRoute = ConsensoTokenRouteImport.update({
  id: '/consenso/$token',
  path: '/consenso/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatisticheRoute =
  AuthenticatedStatisticheRouteImport.update({
    id: '/statistiche',
    path: '/statistiche',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMagazzinoRoute = AuthenticatedMagazzinoRouteImport.update({
  id: '/magazzino',
  path: '/magazzino',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientiRoute = AuthenticatedClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/magazzino': typeof AuthenticatedMagazzinoRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/consenso/$token': typeof ConsensoTokenRoute
  '/prenota/$slug': typeof PrenotaSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/magazzino': typeof AuthenticatedMagazzinoRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/consenso/$token': typeof ConsensoTokenRoute
  '/prenota/$slug': typeof PrenotaSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/clienti': typeof AuthenticatedClientiRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/magazzino': typeof AuthenticatedMagazzinoRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/statistiche': typeof AuthenticatedStatisticheRoute
  '/consenso/$token': typeof ConsensoTokenRoute
  '/prenota/$slug': typeof PrenotaSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/clienti'
    | '/impostazioni'
    | '/magazzino'
    | '/staff'
    | '/statistiche'
    | '/consenso/$token'
    | '/prenota/$slug'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/clienti'
    | '/impostazioni'
    | '/magazzino'
    | '/staff'
    | '/statistiche'
    | '/consenso/$token'
    | '/prenota/$slug'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/agenda'
    | '/_authenticated/clienti'
    | '/_authenticated/impostazioni'
    | '/_authenticated/magazzino'
    | '/_authenticated/staff'
    | '/_authenticated/statistiche'
    | '/consenso/$token'
    | '/prenota/$slug'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ConsensoTokenRoute: typeof ConsensoTokenRoute
  PrenotaSlugRoute: typeof PrenotaSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota/$slug': {
      id: '/prenota/$slug'
      path: '/prenota/$slug'
      fullPath: '/prenota/$slug'
      preLoaderRoute: typeof PrenotaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consenso/$token': {
      id: '/consenso/$token'
      path: '/consenso/$token'
      fullPath: '/consenso/$token'
      preLoaderRoute: typeof ConsensoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistiche': {
      id: '/_authenticated/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof AuthenticatedStatisticheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/magazzino': {
      id: '/_authenticated/magazzino'
      path: '/magazzino'
      fullPath: '/magazzino'
      preLoaderRoute: typeof AuthenticatedMagazzinoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clienti': {
      id: '/_authenticated/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof AuthenticatedClientiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedClientiRoute: typeof AuthenticatedClientiRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedMagazzinoRoute: typeof AuthenticatedMagazzinoRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStatisticheRoute: typeof AuthenticatedStatisticheRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedClientiRoute: AuthenticatedClientiRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedMagazzinoRoute: AuthenticatedMagazzinoRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStatisticheRoute: AuthenticatedStatisticheRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ConsensoTokenRoute: ConsensoTokenRoute,
  PrenotaSlugRoute: PrenotaSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
